# Settings for the game

# Game settings
FPS = 60

# Screen dimensions
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# Player settings
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3

# Shot Settings
SHOT_RADIUS = 5

# Asteroid settings
ASTEROID_MIN_LIFE = 1
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 2  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

# Powerup settings
POWERUP_TIME = 5
POWERUP_SPAWN_RATE = 15
POWERUP_RADIUS = 10